module.exports = {
  ch: {
    plevisit                        : "请访问您的注册邮箱以验证您的帐户！",
    accDisa                         : "您的帐户已禁用！ 请联系申请所有者。",
    userNotFound                    : "找不到用户 请注册",
    serEncou                        : "服务器遇到意外事件，不允许完成请求。 我们抱歉。",
    passNo                          : "密码不匹配！",
    addDNo                          : "所有必需的详细信息都没有到达服务器！",
    useAlE                          : "用户已存在！ 请登录。",
    emailMes                        : "电子邮件将很快发送给您。 请访问您的邮箱并激活该帐户。 激活链接有效期为24小时",
    signsuccess                     : "成功登录",
    wrongCre                        : "错误的凭据！ 或r用户名或密码不正确",
    couldNot                        : "无法登录！ 请再试一次！",
    notReserver                     : "所有必需的详细信息都没有到达服务器！",
    wronpe                          : "输入错误的密码",
    terro                           : "出现技术错误",
    nameChSucc                      : "名称已成功更改",
    serisunatopr                    : "服务器目前无法处理您的请求。 请稍后再试。",
    causesaold                      : "不能使用相同的旧密码",
    passchsucc                      : "密码已成功更改",
    wearunato                       : "我们目前无法处理您的请求。 请稍后再试。",
    unatoret                        : "无法检索交易！",
    logoutsuc                       : "User Logged Out",
    accoActi                        : "GEM电子钱包帐户激活",
    accoActiTextpartOne             : "您收到这个是因为您（或其他人）使用您的邮件ID注册了GEM钱包",
    accoActiTextpartTwo             :"如果你是目标收件人，那么：",
    accoActiTextpartThree           : "请点击以下链接，或将其粘贴到浏览器中以完成激活过程：",
    accoActiTextpartFour            : "如果您没有注册GEM电子钱包，请忽略此电子邮件，您的电子邮件将不会用于注册。",
    useNoPenReg                     : "找不到用户 请输入注册邮箱ID",
    walPassRes                      : "GEM钱包密码重置",
    walPassResTex1                  : "您收到此信息是因为您（或其他人）请求重置您帐户的密码。",
    walPassResTex2                  : "请点击以下链接，或将其粘贴到浏览器中以完成以下过程：",
    walPassResTex3                  : "如果您没有请求，请忽略此电子邮件，密码将保持不变。",
    walPassResMess                  : "电子邮件将发送到您的邮件。 请访问您的邮箱并遵循说明",
    walPassResMessInserEr           : "内部服务器错误。 请稍后再试。",
    LinkExp                         : "链接已过期！",
    soryouaclin                     : "对不起，您的激活链接已过期！",
    pleRegyouRespas                 : "您的激活链接已过期。 请在登录页面上重新生成重置密码链接",
    cliHeL                          : "点击此处登录",
    yoPassHaCH                      : "您的密码已被更改",
    yoCanEnAnAle                    : "您不能输入已使用的密码",
    suReEmail                       : "GEM推荐电子邮件",
    WeUntoAc                        : "我们现在无法解锁帐户！ 请再试一次。",
    TranSuccP                       : "交易成功处理",
    TraFaPlea                       : "交易失败！ 请稍后再试。",
    InsuFuTo                        : "资金不足以执行此交易。",
    InvEthAdd                       : "无效的地址！ 请输入有效的地址，再试一次！",
    SerUseLogStaErrTex              : "您的邮箱未激活，请激活您的邮箱"
  },
  en: {
    plevisit                        : "Please visit your Registered Mailbox to verify your Account!",
    accDisa                         : "Your account has been disabled! Please contact application owner.",
    userNotFound                    : "User Not Found. Please Sign Up",
    passNo                          : "Passwords Do Not Match!",
    addDNo                          : "All the required details are not reaching the server!",
    useAlE                          : "User Already Exists! Please Login.",
    serEncou                        : "The server encountered something unexpected that didn't allow it to complete the request. We apologize.",
    emailMes                        : "An Email will be sent to you shortly. Please visit your mailbox and activate the account. Activation link is valid for 24 Hours",
    signsuccess                     : "Signed in Successfully",
    wrongCre                        : "Wrong Credentials! Either Username or Password is incorrect",
    couldNot                        : "Could Not Sign In! Please Try Again!",
    notReserver                     : "All the required details are not reaching the server!",
    wronpe                          : "Wrong Password Entered",
    terro                           : "Technical Error Occured",
    nameChSucc                      : "Name Changed Successfully",
    serisunatopr                    : "Server is unable to process your request at this time. Please try again later.",
    causesaold                      : "Cannot use the same old password",
    passchsucc                      : "Password Changed Successfully",
    wearunato                       : "We are unable to process your request at this time. Please try again later.",
    unatoret                        : "Unable To Retrieve Transactions!",
    logoutsuc                       : "User Logged Out",
    accoActi                        : 'GEM Wallet Account Activation',
    accoActiTextpartOne             : "You are receiving this because you (or someone else) have signed up to the GEM wallet using your mail ID.",
    accoActiTextpartTwo             :"If you are the intended recipient then:",
    accoActiTextpartThree           : "Please click on the following link, or paste this into your browser to complete the activation process:",
    accoActiTextpartFour            : "If you did not sign up to the GEM Wallet, please ignore this email and your email will not be used for Signup.",
    useNoPenReg                     : "User Not Found. Please Enter Registered Mail Id",
    walPassRes                      : "GEM Wallet Password Reset",
    walPassResTex1                  : "You are receiving this because you (or someone else) have requested the reset of the password for your account.",
    walPassResTex2                  : "Please click on the following link, or paste this into your browser to complete the process:",
    walPassResTex3                  : "If you did not request this, please ignore this email and your password will remain unchanged.",
    walPassResMess                  : "An Email will be sent to your mail. Please visit your mailbox and follow instructions",
    walPassResMessInserEr           : "Internal Server Error. Please try again later.",
    LinkExp                         : "Link Expired!",
    soryouaclin                     : "Sorry Your Activation Link is Expired!",
    pleRegyouRespas                 : "Your activation link is expired. Please regenerate your reset password link on the login page",
    cliHeL                          : "Click here to Login",
    yoPassHaCH                      : "Your password has been changed",
    yoCanEnAnAle                    : "You cannot enter an already used password",
    suReEmail                       : "GEM Referral Email",
    WeUntoAc                        : "We are unable to unlock account as of now! Please try again.",
    TranSuccP                       : "Transaction is successfully Processed",
    TraFaPlea                       : "Transaction Failed! Please try again later.",
    InsuFuTo                        : "Insufficient Funds to perform this transaction.",
    InvEthAdd                       : "Invalid Ethereum Address! Please enter a valid Address and Try Again!",
    SerUseLogStaErrTex              : "Your email is not verified, Please visit your mailbox."
  }
};
